redmine_dmsf/config/routes.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  #
  # dmsf controller
  #   /projects/<project>/dmsf
  #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
  ##
  post '/projects/:id/dmsf/create', :controller => 'dmsf', :action => 'create'
  get '/projects/:id/dmsf/notify/activate', :controller => 'dmsf', :action => 'notify_activate', :as => 'notify_activate_dmsf'
  get '/projects/:id/dmsf/notify/deactivate', :controller => 'dmsf', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf'
  get '/projects/:id/dmsf/delete', :controller => 'dmsf', :action => 'delete', :as => 'delete_dmsf'
  post '/projects/:id/dmsf/save', :controller => 'dmsf', :action => 'save'
  post '/projects/:id/dmsf/save/root', :controller => 'dmsf', :action => 'save_root'
  post '/projects/:id/dmsf/entries', :controller => 'dmsf', :action => 'entries_operation'
  post '/projects/:id/dmsf/tag_changed', :controller => 'dmsf', :action => 'tag_changed', :as => 'tag_changed'
  post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries', :as => 'delete_entries'
  post '/projects/:id/dmsf/entries/email', :controller => 'dmsf', :action => 'entries_email'
  get '/projects/:id/dmsf/entries/download_email_entries', :controller => 'dmsf', :action => 'download_email_entries', :as => 'download_email_entries'
  get '/projects/:id/dmsf/lock', :controller => 'dmsf', :action => 'lock', :as => 'lock_dmsf'
  get '/projects/:id/dmsf/unlock', :controller => 'dmsf', :action => 'unlock', :as => 'unlock_dmsf'
  get '/projects/:id/dmsf/', :controller => 'dmsf', :action => 'show', :as => 'dmsf_folder'
  get '/projects/:id/dmsf/new', :controller => 'dmsf', :action => 'new', :as => 'new_dmsf'
  get '/projects/:id/dmsf/edit', :controller=> 'dmsf', :action => 'edit', :as => 'edit_dmsf'
  get '/projects/:id/dmsf/edit/root', :controller=> 'dmsf', :action => 'edit_root', :as => 'edit_root_dmsf'
  get '/projects/:id/dmsf/trash', :controller => 'dmsf', :action => 'trash', :as => 'trash_dmsf'
  get '/projects/:id/dmsf/restore', :controller => 'dmsf', :action => 'restore', :as => 'restore_dmsf'

  #
  # dmsf_state controller
  #   /projects/<project>/dmsf/state
  ##
  post '/projects/:id/dmsf/state', :controller => 'dmsf_state', :action => 'user_pref_save'

  #
  #  dmsf_upload controller
  #   /projects/<project>/dmsf/upload - dmsf_upload controller
  ##

  post '/projects/:id/dmsf/upload/files', :controller => 'dmsf_upload', :action => 'upload_files'
  post '/projects/:id/dmsf/upload/file', :controller => 'dmsf_upload', :action => 'upload_file'
  post '/projects/:id/dmsf/upload/commit', :controller => 'dmsf_upload', :action => 'commit_files'
  
  #
  # dmsf_files controller
  #   /dmsf/files/<file id>
  ##
  get '/dmsf/files/:id/notify/activate', :controller => 'dmsf_files', :action => 'notify_activate', :as => 'notify_activate_dmsf_files'
  get '/dmsf/files/:id/notify/deactivate', :controller => 'dmsf_files', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf_files'
  get '/dmsf/files/:id/lock', :controller => 'dmsf_files', :action => 'lock', :as => 'lock_dmsf_files'
  get '/dmsf/files/:id/unlock', :controller => 'dmsf_files', :action => 'unlock', :as => 'unlock_dmsf_files'
  post '/dmsf/files/:id/delete', :controller => 'dmsf_files', :action => 'delete', :as => 'delete_dmsf_files'
  post '/dmsf/files/:id/revision/create', :controller => 'dmsf_files', :action => 'create_revision'
  get '/dmsf/files/:id/revision/delete', :controller => 'dmsf_files', :action => 'delete_revision', :as => 'delete_revision'
  get '/dmsf/files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => '' # Otherwise will not route nil download param
  get '/dmsf/files/:id/download/:download', :controller => 'dmsf_files', :action => 'show', :as => 'download_revision'
  get '/dmsf/files/:id/view', :controller => 'dmsf_files', :action => 'view'
  get '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'show', :as => 'dmsf_file'  
  delete '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'delete'
  get '/dmsf/files/:id/restore', :controller => 'dmsf_files', :action => 'restore', :as => 'restore_dmsf_file'
  
  # Just to keep backward compatibility with old external direct links
  get '/dmsf_files/:id', :controller => 'dmsf_files', :action => 'show'
  get '/dmsf_files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => ''

  #
  # files_copy controller
  #   /dmsf/files/<file id>/copy
  ##
  post '/dmsf/files/:id/copy/create', :controller => 'dmsf_files_copy', :action => 'create'
  post '/dmsf/files/:id/copy/move', :controller => 'dmsf_files_copy', :action => 'move'
  get '/dmsf/files/:id/copy', :controller => 'dmsf_files_copy', :action => 'new', :as => 'copy_file'

  #
  # folders_copy controller
  #   /dmsf/folders/<folder id>/copy
  ##
  #verify :method => :post, :only => [:copy_to], :render => { :nothing => true, :status => :method_not_allowed }
  post '/dmsf/folders/:id/copy/to', :controller => 'dmsf_folders_copy', :action => 'copy_to'
  get '/dmsf/folders/:id/copy', :controller => 'dmsf_folders_copy', :action => 'new', :as => 'copy_folder'

  #
  # DAV4Rack implementation of Webdav [note: if changing path you'll need to update lib/redmine_dmsf/webdav/no_parse.rb also]
  #   /dmsf/webdav
  mount DAV4Rack::Handler.new(
    :root_uri_path => "/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller
  ), :at => "/dmsf/webdav"
  
  # Approval workflow    
  resources :dmsf_workflows do
    member do
      get 'autocomplete_for_user'
      get 'action'
      get 'assign'
      get 'log'
      post 'new_action'
      get 'start'
      post 'assignment'
    end
  end
  
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'add_step', :id => /\d+/, :via => :post
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'remove_step', :id => /\d+/, :via => :delete
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'reorder_steps', :id => /\d+/, :via => :put    
  
  # Links
  resources :dmsf_links do
    member do
      get 'restore'
    end    
  end  
  
end

redmine_dmsf/app/helpers/dmsf_helper.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011   Vít Jonáš <vit.jonas@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require 'tmpdir'
require 'digest/md5'

module DmsfHelper

  def self.temp_dir
    Dir.tmpdir
  end

  def self.temp_filename(filename)
    filename = sanitize_filename(filename)
    timestamp = DateTime.now.strftime("%y%m%d%H%M%S")
    while File.exist?(File.join(temp_dir, "#{timestamp}_#{filename}"))
      timestamp.succ!
    end
    "#{timestamp}_#{filename}"
  end
  
  def self.sanitize_filename(filename)
    # get only the filename, not the whole path
    just_filename = File.basename(filename.gsub('\\\\', '/'))

    # replace all non alphanumeric, hyphens or periods with underscore
    just_filename = just_filename.gsub(/[^\w\.\-]/,'_')

    unless just_filename =~ %r{^[a-zA-Z0-9_\.\-]*$}
      # keep the extension if any
      extension = $1 if just_filename =~ %r{(\.[a-zA-Z0-9]+)$}
      just_filename = Digest::MD5.hexdigest(just_filename) << extension
    end
    
    just_filename
  end
  
  def self.filetype_css(filename)
    extension = File.extname(filename)
    extension = extension[1, extension.length-1]
    if File.exists?("#{File.dirname(__FILE__)}/../../assets/images/filetypes/#{extension}.png")
      return "filetype-#{extension}";
    else
      return Redmine::MimeType.css_class_of(filename)
    end
  end

  def plugin_asset_path(plugin, asset_type, source)    
    return "#{Redmine::Utils.relative_url_root}/plugin_assets/#{plugin}/#{asset_type}/#{source}"           
  end

  def self.to_time(obj)
    #Right, enough of bugs, let's try a better approach here.
    return if !obj
    return obj.to_time(ActiveRecord::Base.default_timezone) if obj.is_a?(String)

    # Why can't Mysql::Time conform to time object? - without a utc? method it breaks redmine's
    # rendering method, so we convert it to string, and back into time - not the most efficient 
    # of methods - however seems functional. Not sure if MySQL
    return obj.to_s.to_time(ActiveRecord::Base.default_timezone) if obj.class.name == 'Mysql::Time'
    return obj
  end  
  
end

redmine_dmsf/app/views/dmsf/edit.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011   Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012   Daniel Munn  <dan.munn@munnster.co.uk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<% html_title(l(:dmsf)) %>

<div class="contextual">
  <% if User.current.allowed_to?(:folder_manipulation, @project) && params[:action] == 'edit' %>
    <% unless @folder.locked? %>
       <%= link_to(l(:button_lock),
          lock_dmsf_path(:id => @project, :folder_id => @folder),
          :title => l(:title_lock_file),
          :class => 'icon icon-dmsf-lock') %>  
      <% if @folder.notification %>              
          <%= link_to(l(:label_notifications_off),
           notify_deactivate_dmsf_path(:id => @project, :folder_id => @folder),
            :title => l(:title_notifications_active_deactivate),
            :class => 'icon icon-notification-on') %>
        <% else %>              
          <%= link_to(l(:label_notifications_on),
            notify_activate_dmsf_path(:id => @project, :folder_id => @folder),
            :title => l(:title_notifications_not_active_activate),
            :class => 'icon icon-notification-off') %>
        <% end %>      
      <%= link_to(l(:label_link_to), 
        new_dmsf_link_path(:project_id => @project.id, :dmsf_folder_id => @folder.id, :type => 'link_to'),
        :title => l(:title_create_link), 
        :class => 'icon icon-link') %>
      <%= link_to(l(:button_copy), copy_folder_path(:id => @folder),
        :title => l(:title_copy), :class => 'icon icon-copy') %>      
      <%= link_to(l(:button_delete),
        delete_dmsf_path(:id => @project, :folder_id => @folder),
        :data => {:confirm => l(:text_are_you_sure)},            
        :title => l(:title_delete),
        :class => 'icon icon-del') %> 
    <% else %>
      <% if (!@folder.locked_for_user? || User.current.allowed_to?(:force_file_unlock, @project)) && @folder.unlockable? %>
        <%= link_to(l(:button_unlock),
          unlock_dmsf_path(:id => @project, :folder_id => @folder),
            :title => l(:title_unlock_file),
            :class => 'icon icon-dmsf-unlock')%>
      <% end %>        
    <% end %>   
  <% end %>
</div>

<% create = @pathfolder == @parent %>
<%= render(:partial => 'path', :locals => {:folder => @pathfolder, :filename => create ? l(:heading_new_folder) : nil}) %>  

<%= form_for(@folder, :url => {:action => create ? 'create' : 'save', :id => @project, :folder_id => @folder, :parent_id => @parent},
  :html => {:method=>:post}) do |f| %>
  <%= error_messages_for(@folder) %>
  <div class="box dmsf_detail">
    <div class="clear">
      <div class="splitcontentleft">
        <p>
          <%= label_tag('dmsf_folder_title', "#{l(:label_title)}:") %>
          <%= f.text_field(:title, :size => '32', :required => true) %>
        </p>
      </div>
      <div class="splitcontentright">
        <p>
          <%= label_tag('', "#{l(:field_folder)}:") %>
          <%= f.select(:dmsf_folder_id, 
            options_for_select(DmsfFolder.directory_tree(@project, @folder), 	
            :selected => @parent? @parent.id : (@pathfolder.id if @pathfolder)))                                                  
          %>				
        </p>
      </div>
    </div>
    <p class="no-ident">
      <%= label_tag('dmsf_folder_description', "#{l(:label_description)}:") %>
    </p>
    <div class="wiki data clear">
      <%= f.text_area(:description, :rows => 15, :class => 'wiki-edit') %>
    </div>
    <% values = @folder ? @folder.custom_field_values : @parent ? @parent.custom_field_values : DmsfFolder.new(:project => @project).custom_field_values %>
    <% values.each do |value| %>
      <p><%= custom_field_tag_with_label(:dmsf_folder, value) %></p>
    <% end %>
  </div>
  <%= submit_tag(create ? l(:submit_create) : l(:submit_save)) %>
<% end %>

<%= wikitoolbar_for 'dmsf_folder_description' %>

redmine_dmsf/app/views/dmsf/show.html.erb
<%#=
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% html_title(l(:dmsf)) %>
<div class="contextual">
  <% if @folder_manipulation_allowed %>    
    <% if @folder.nil? %>      
      <%= link_to(l(:button_edit), 
        edit_root_dmsf_path(:id => @project),
        :title => l(:link_edit, :title => l(:link_documents)), 
        :class => 'icon icon-edit') %>
    <% elsif !@locked_for_user %>      
      <%= link_to(l(:button_edit), 
        edit_dmsf_path(:id => @project, :folder_id => @folder),
        :title => l(:link_edit, :title => h(@folder.title)), 
        :class => 'icon icon-edit') %>
    <% end %>
    <% if @folder && (!@locked_for_user || User.current.allowed_to?(:force_file_unlock, @project)) %>
      <% if @folder.locked? %>
        <% unless @folder.unlockable? %>
          <%= link_to(l(:button_unlock),
            :title => l(:title_folder_parent_locked, :name => @folder.folder.lock.reverse[0].folder.title),
            :class => 'icon icon-dmsf-unlock') if @folder %>
        <% else %>
          <%= link_to(l(:button_unlock),
            unlock_dmsf_path(:id => @project, :folder_id => @folder, :current => request.url),
            :title => l(:title_unlock_folder),
           :class => 'icon icon-dmsf-unlock') if @folder %>          
        <% end %>
      <% else %>
        <%= link_to(l(:button_lock),
          lock_dmsf_path(:id => @project, :folder_id => @folder, :current => request.url),
          :title => l(:title_lock_folder),
          :class => 'icon icon-dmsf-lock') if @folder %>
      <% end %>
    <% end %>
    <% unless @folder %>         
      <% if @project.dmsf_notification %>        
        <%= link_to(l(:label_notifications_off), 
          notify_deactivate_dmsf_path(:id => @project),
          :title => l(:title_notifications_active_deactivate), 
          :class => 'icon icon-notification-on') %>
      <% else %>        
        <%= link_to(l(:label_notifications_on),
          notify_activate_dmsf_path(:id => @project),
          :title => l(:title_notifications_active_deactivate), 
          :class => 'icon icon-notification-off') %>
      <% end %> 
    <% else %>
      <% if @folder.notification %>
          <%= link_to(l(:label_notifications_off),
            notify_deactivate_dmsf_path(:id => @project, :folder_id => @folder),
            :title => l(:title_notifications_active_deactivate),
            :class => 'icon icon-notification-on') %>
        <% else %>
          <%= link_to(l(:label_notifications_on),
            notify_activate_dmsf_path(:id => @project, :folder_id => @folder),
            :title => l(:title_notifications_not_active_activate),
            :class => 'icon icon-notification-off') %>
        <% end %>    
    <% end %>    
    <% if @file_manipulation_allowed %>      
      <%= link_to(l(:label_link_from), 
        new_dmsf_link_path(:project_id => @project.id, :dmsf_folder_id => @folder ? @folder.id : @folder, :type => 'link_from'),
        :title => l(:title_create_link), 
        :class => 'icon icon-link') unless @locked_for_user %>
    <% end %>    
    <%= link_to(l(:link_create_folder), 
      new_dmsf_path(:id => @project, :parent_id => @folder),
      :title => l(:link_create_folder), 
      :class => 'icon icon-add') unless @locked_for_user %>
  <% end %>
  <%= link_to_if(@trash_enabled, l(:link_trash_bin), trash_dmsf_path(@project),
    :title => l(:link_trash_bin), :class => 'icon icon-del') if @trash_visible %>
</div>

<%= render(:partial => 'path', :locals => {:folder => @folder, :filename => nil}) %>

<div class="dmsf-header">
  <div class="wiki">
    <%= textilizable(@folder ? @folder.description : @project.dmsf_description) %>
  </div>    
</div>

<%= error_messages_for('dmsf_workflow') %>

<%= form_tag({:action => :entries_operation, :id => @project, :folder_id => @folder}, :method => :post,
  :class => 'dmfs_entries', :id => 'entries_form') do %>
  <%= hidden_field_tag('action') %>
  <div class="controls" style="float: left">
    <%= submit_tag(l(:button_download), :title => l(:title_download_checked), :name => 'download_entries') %>
    <%= submit_tag(l(:field_mail), :title => l(:title_send_checked_by_email), :name => 'email_entries') %>
    <%= submit_tag(l(:button_delete), :title => l(:title_delete_checked), :name => 'delete_entries') %>
  </div>
  <% values = @folder ? @folder.custom_field_values : @parent ? @parent.custom_field_values : DmsfFolder.new(:project => @project).custom_field_values %>
  <% unless values.empty? %>
    <div class="controls" style="float: right">               
      <%= custom_field_tag_with_label(
        :dmsf_folder, 
        CustomValue.new(:custom_field_id => params[:custom_field_id].present? ? params[:custom_field_id] : values.first.custom_field_id, :value => params[:custom_value])) %>
    </div>  
  <% end %>    
  <table class="display entries" id="browser">
    <thead>
      <tr id="root">
        <th class="check">
          <input id="check_all_entries" title="<%= l(:title_check_uncheck_all_for_zip_download_or_email) %>" type="checkbox" />
        </th>
        <th><%= l(:link_title) %></th>
        <th><%= l(:link_size) %></th>
        <th><%= l(:link_modified) %></th>
        <th title="<%= l(:label_version) %>"><%= l(:link_ver) %></th>
        <th><%= l(:link_workflow) %></th>
        <th><%= l(:link_author) %></th>
        <th></th>
        <th class="hidden"></th>
        <th class="hidden"></th>
        <th class="hidden"></th>
        <th class="hidden"></th>
      </tr>
    </thead>
  <tbody>       
  <% @subfolders.each do |subfolder| %>    
    <tr class="dir">
      <%= render(:partial => 'dir', 
        :locals => { 
          :project => @project, 
          :subfolder => subfolder, 
          :link => nil,
          :id => subfolder.id, 
          :name => 'subfolders[]', 
          :title => subfolder.title }) %>
    </tr>
  <% end %>  
  <% @dir_links.each do |link| %>    
    <tr class="gray">
      <%= render(:partial => 'dir', 
        :locals => { 
          :project => link.target_project, 
          :subfolder => link.target_folder, 
          :link => link,
          :id => link.id, 
          :name => 'dir_links[]', 
          :title => link.name }) %>
    </tr>
  <% end %>        
  <% @files.each do |file| %>
    <% unless file.last_revision %>      
      <% Rails.logger.error "Error: dmsf_file id #{file.id} has no revision!" %>
      <% next %>
    <% end %>         
    <tr class="file">
      <%= render(:partial => 'file', :locals => { 
          :project => @project, 
          :file => file, 
          :link => nil,
          :id => file.id,
          :name => 'files[]',
          :title => file.title }) %>
    </tr>
  <% end %>
  <% @file_links.each do |link| %>
    <% unless link.target_file.last_revision %>      
      <% Rails.logger.error "Error: dmsf_file id #{link.target_id} has no revision!" %>
      <% next %>
    <% end %>         
    <tr class="gray">
      <%= render(:partial => 'file', :locals => { 
          :project => link.target_project, 
          :file => link.target_file, 
          :link => link,
          :id => link.id,
          :name => 'file_links[]',
          :title => link.name }) %>
    </tr>
  <% end %>
  </tbody>
  </table>  
<% end %>   

<script type="text/javascript">
  $('#entries_delete_button').click(function() {
    if(window.confirm("<%= l(:text_are_you_sure) %>")) {
      $('#entries_form').attr('action', "<%= delete_entries_path(:id => @project, :folder_id => @folder) %>");      
      $('#entries_form').submit();
    }
  });
  
  $('.list_cf').change(function() {
    $('#entries_form').attr('action', "<%= tag_changed_path(:id => @project, :folder_id => @folder) %>");
    $('#entries_form').submit();   
  });

  $('#check_all_entries').click(function() {    
    $('input[type=checkbox]', $('#browser > tbody')).prop('checked', this.checked);    
  });  
</script>

<%
  if I18n.locale && !I18n.locale.to_s.match(/^en.*/)
    sUrl = "jquery.dataTables/#{I18n.locale.to_s.downcase}.json" 
  else
    sUrl = 'jquery.dataTables/en.json'
  end    
%>

<% content_for :header_tags do %>    
  <%= stylesheet_link_tag 'plupload/jquery.ui.plupload.css', :plugin => 'redmine_dmsf' %>
  <%= stylesheet_link_tag 'jquery.dataTables/jquery-ui.dataTables.css', :plugin => 'redmine_dmsf' %>  
  <%= javascript_include_tag 'jquery.dataTables/jquery.dataTables.min.js', :plugin => 'redmine_dmsf' %>

  <script type="text/javascript">    
    $(document).ready(function() {
      $('#browser').dataTable({
        'bJQueryUI': true,
        'oLanguage': {
                'sUrl': "<%= plugin_asset_path(:redmine_dmsf, 'javascripts', sUrl) %>"
        },
                'bAutoWidth': false,
        'bPaginate': false,
        'aaSorting': [[1,'asc']],
        'aaSortingFixed': [[8,'asc']],
        'aoColumnDefs': [
          { 'bSearchable': false, 'aTargets': [0, 7, 8, 9] },
          { 'bSortable': false, 'aTargets': [0, 7, 8] },
          { 'iDataSort': 9, 'aTargets': [ 2 ] },
          { 'iDataSort': 10, 'aTargets': [ 3 ] },
          { 'iDataSort': 11, 'aTargets': [ 4 ] }
        ],
        'fnInitComplete': function() {
           jQuery('div.controls').prependTo(jQuery('#browser_wrapper div.fg-toolbar')[0]);
        },
        'fnInfoCallback': function( oSettings, iStart, iEnd, iMax, iTotal, sPre ) {
           return "<%= l(:label_number_of_folders)%>: <%= @subfolders.count + @dir_links.count %>, <%= l(:label_number_of_documents)%>: <%= @files.count + @file_links.count %>";
        }
      });

      $('[data-downloadurl]').each(function() {
        var url = this.getAttribute('data-downloadurl');
        if (this.addEventListener) {
          this.addEventListener('dragstart', function(e) {
            if (e.dataTransfer) {
              e.dataTransfer.setData('DownloadURL', url);
            }
          },false);
        }
      });

      $('#entries_form').submit(function () {
          $(this).removeAttr('data-submitted');
      });
    });   
  </script>
<% end %>

<%= render(:partial => 'dmsf_upload/multi_upload') if (@file_manipulation_allowed && !@locked_for_user) %>