redmine_dmsf/config/routes.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  #
  # dmsf controller
  #   /projects/<project>/dmsf
  #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
  ##
  post '/projects/:id/dmsf/create', :controller => 'dmsf', :action => 'create'
  get '/projects/:id/dmsf/notify/activate', :controller => 'dmsf', :action => 'notify_activate', :as => 'notify_activate_dmsf'
  get '/projects/:id/dmsf/notify/deactivate', :controller => 'dmsf', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf'
  get '/projects/:id/dmsf/delete', :controller => 'dmsf', :action => 'delete', :as => 'delete_dmsf'
  post '/projects/:id/dmsf/save', :controller => 'dmsf', :action => 'save'
  post '/projects/:id/dmsf/save/root', :controller => 'dmsf', :action => 'save_root'
  post '/projects/:id/dmsf/entries', :controller => 'dmsf', :action => 'entries_operation'
  post '/projects/:id/dmsf/tag_changed', :controller => 'dmsf', :action => 'tag_changed', :as => 'tag_changed'
  post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries', :as => 'delete_entries'
  post '/projects/:id/dmsf/entries/email', :controller => 'dmsf', :action => 'entries_email'
  get '/projects/:id/dmsf/entries/download_email_entries', :controller => 'dmsf', :action => 'download_email_entries', :as => 'download_email_entries'
  get '/projects/:id/dmsf/lock', :controller => 'dmsf', :action => 'lock', :as => 'lock_dmsf'
  get '/projects/:id/dmsf/unlock', :controller => 'dmsf', :action => 'unlock', :as => 'unlock_dmsf'
  get '/projects/:id/dmsf/', :controller => 'dmsf', :action => 'show', :as => 'dmsf_folder'
  get '/projects/:id/dmsf/new', :controller => 'dmsf', :action => 'new', :as => 'new_dmsf'
  get '/projects/:id/dmsf/edit', :controller=> 'dmsf', :action => 'edit', :as => 'edit_dmsf'
  get '/projects/:id/dmsf/edit/root', :controller=> 'dmsf', :action => 'edit_root', :as => 'edit_root_dmsf'
  get '/projects/:id/dmsf/trash', :controller => 'dmsf', :action => 'trash', :as => 'trash_dmsf'
  get '/projects/:id/dmsf/restore', :controller => 'dmsf', :action => 'restore', :as => 'restore_dmsf'

  #
  # dmsf_state controller
  #   /projects/<project>/dmsf/state
  ##
  post '/projects/:id/dmsf/state', :controller => 'dmsf_state', :action => 'user_pref_save'

  #
  #  dmsf_upload controller
  #   /projects/<project>/dmsf/upload - dmsf_upload controller
  ##

  post '/projects/:id/dmsf/upload/files', :controller => 'dmsf_upload', :action => 'upload_files'
  post '/projects/:id/dmsf/upload/file', :controller => 'dmsf_upload', :action => 'upload_file'
  post '/projects/:id/dmsf/upload/commit', :controller => 'dmsf_upload', :action => 'commit_files'
  
  #
  # dmsf_files controller
  #   /dmsf/files/<file id>
  ##
  get '/dmsf/files/:id/notify/activate', :controller => 'dmsf_files', :action => 'notify_activate', :as => 'notify_activate_dmsf_files'
  get '/dmsf/files/:id/notify/deactivate', :controller => 'dmsf_files', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf_files'
  get '/dmsf/files/:id/lock', :controller => 'dmsf_files', :action => 'lock', :as => 'lock_dmsf_files'
  get '/dmsf/files/:id/unlock', :controller => 'dmsf_files', :action => 'unlock', :as => 'unlock_dmsf_files'
  post '/dmsf/files/:id/delete', :controller => 'dmsf_files', :action => 'delete', :as => 'delete_dmsf_files'
  post '/dmsf/files/:id/revision/create', :controller => 'dmsf_files', :action => 'create_revision'
  get '/dmsf/files/:id/revision/delete', :controller => 'dmsf_files', :action => 'delete_revision', :as => 'delete_revision'
  get '/dmsf/files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => '' # Otherwise will not route nil download param
  get '/dmsf/files/:id/download/:download', :controller => 'dmsf_files', :action => 'show', :as => 'download_revision'
  get '/dmsf/files/:id/view', :controller => 'dmsf_files', :action => 'view'
  get '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'show', :as => 'dmsf_file'  
  delete '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'delete'
  get '/dmsf/files/:id/restore', :controller => 'dmsf_files', :action => 'restore', :as => 'restore_dmsf_file'
  
  # Just to keep backward compatibility with old external direct links
  get '/dmsf_files/:id', :controller => 'dmsf_files', :action => 'show'
  get '/dmsf_files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => ''

  #
  # files_copy controller
  #   /dmsf/files/<file id>/copy
  ##
  post '/dmsf/files/:id/copy/create', :controller => 'dmsf_files_copy', :action => 'create'
  post '/dmsf/files/:id/copy/move', :controller => 'dmsf_files_copy', :action => 'move'
  get '/dmsf/files/:id/copy', :controller => 'dmsf_files_copy', :action => 'new', :as => 'copy_file'

  #
  # folders_copy controller
  #   /dmsf/folders/<folder id>/copy
  ##
  #verify :method => :post, :only => [:copy_to], :render => { :nothing => true, :status => :method_not_allowed }
  post '/dmsf/folders/:id/copy/to', :controller => 'dmsf_folders_copy', :action => 'copy_to'
  get '/dmsf/folders/:id/copy', :controller => 'dmsf_folders_copy', :action => 'new', :as => 'copy_folder'

  #
  # DAV4Rack implementation of Webdav [note: if changing path you'll need to update lib/redmine_dmsf/webdav/no_parse.rb also]
  #   /dmsf/webdav
  mount DAV4Rack::Handler.new(
    :root_uri_path => "/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller
  ), :at => "/dmsf/webdav"
  
  # Approval workflow    
  resources :dmsf_workflows do
    member do
      get 'autocomplete_for_user'
      get 'action'
      get 'assign'
      get 'log'
      post 'new_action'
      get 'start'
      post 'assignment'
    end
  end
  
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'add_step', :id => /\d+/, :via => :post
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'remove_step', :id => /\d+/, :via => :delete
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'reorder_steps', :id => /\d+/, :via => :put    
  
  # Links
  resources :dmsf_links do
    member do
      get 'restore'
    end    
  end  
  
end

redmine_dmsf/app/controllers/dmsf_files_controller.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class DmsfFilesController < ApplicationController
  unloadable
  
  menu_item :dmsf
  
  before_filter :find_file, :except => [:delete_revision]
  before_filter :find_revision, :only => [:delete_revision]
  before_filter :authorize

  helper :all
  helper :dmsf_workflows

  def view
    @revision = @file.last_revision
    check_project(@revision.file)    
    begin
      log_activity('downloaded')
      access = DmsfFileRevisionAccess.new(:user_id => User.current.id, 
        :dmsf_file_revision_id => @revision.id,
        :action => DmsfFileRevisionAccess::DownloadAction)
      access.save!
      send_file(@revision.disk_file,
        :filename => filename_for_content_disposition(@revision.name),
        :type => @revision.detect_content_type,
        :disposition => 'inline')
    rescue ActionController::MissingFile => e
      logger.error e.message
      render_404
    end 
  end
    
  def show
    # The download is put here to provide more clear and usable links
    if params.has_key?(:download)
      if params[:download].blank?
        @revision = @file.last_revision
      else
        @revision = DmsfFileRevision.find(params[:download].to_i)
        if @revision.file != @file
          render_403
          return
        end        
      end
      check_project(@revision.file)
      begin
        log_activity('downloaded')
        access = DmsfFileRevisionAccess.new(:user_id => User.current.id, :dmsf_file_revision_id => @revision.id, 
          :action => DmsfFileRevisionAccess::DownloadAction)
        access.save!
        send_file(@revision.disk_file, 
          :filename => filename_for_content_disposition(@revision.name),
          :type => @revision.detect_content_type, 
          :disposition => 'attachment')
      rescue ActionController::MissingFile => e
        logger.error e.message
        render_404
      end
      return
    end
    
    @revision = @file.last_revision    
    @file_delete_allowed = User.current.allowed_to?(:file_delete, @project)    
    @revision_pages = Paginator.new @file.revisions.visible.count, params['per_page'] ? params['per_page'].to_i : 25, params['page']
    
    render :layout => !request.xhr?
  end
  
  def create_revision
    if params[:dmsf_file_revision]
      if @file.locked_for_user?
        flash[:error] = l(:error_file_is_locked)        
      else        
        revision = DmsfFileRevision.new(params[:dmsf_file_revision])

        revision.file = @file        
        last_revision = @file.last_revision
        revision.source_revision = last_revision
        revision.user = User.current

        revision.major_version = last_revision.major_version
        revision.minor_version = last_revision.minor_version      
        version = params[:version].to_i
        file_upload = params[:file_upload]
        unless file_upload
          revision.disk_filename = last_revision.disk_filename
          revision.increase_version(version, false)
          revision.mime_type = last_revision.mime_type
          revision.size = last_revision.size
        else
          revision.increase_version(version, true)
          revision.size = file_upload.size
          revision.disk_filename = revision.new_storage_filename
          revision.mime_type = Redmine::MimeType.of(file_upload.original_filename)
        end      

        @file.name = revision.name        

        if revision.valid? && @file.valid?
          revision.save!
          revision.assign_workflow(params[:dmsf_workflow_id])
          if file_upload
            revision.copy_file_content(file_upload)
          end

          if @file.locked? && !@file.locks.empty?
            begin
              @file.unlock!
              flash[:notice] = "#{l(:notice_file_unlocked)}, "
            rescue Exception => e
              logger.error "Cannot unlock the file: #{e.message}"
            end
          end
          @file.save!
          @file.set_last_revision revision

          flash[:notice] = (flash[:notice].nil? ? '' : flash[:notice]) + l(:notice_file_revision_created)
          log_activity('new revision')
          begin            
            recipients = DmsfMailer.get_notify_users(@project, [@file])
            recipients.each do |u|
              DmsfMailer.files_updated(u, @project, [@file]).deliver
            end                        
            if Setting.plugin_redmine_dmsf[:dmsf_display_notified_recipients] == '1'
              unless recipients.empty?
                to = recipients.collect{ |r| r.name }.first(DMSF_MAX_NOTIFICATION_RECEIVERS_INFO).join(', ')
                to << ((recipients.count > DMSF_MAX_NOTIFICATION_RECEIVERS_INFO) ? ',...' : '.')
                flash[:warning] = l(:warning_email_notifications, :to => to)
              end
            end
          rescue Exception => e
            logger.error "Could not send email notifications: #{e.message}"
          end          
        end
      end
    end
    redirect_to :back
  end

  def delete    
    if @file
      commit = params[:commit] == 'yes'
      if @file.delete(commit)
        flash[:notice] = l(:notice_file_deleted)
        if commit
          log_activity('deleted')
          begin
            DmsfMailer.get_notify_users(@project, [@file]).each do |u|
              DmsfMailer.files_deleted(u, @project, [@file]).deliver
            end
          rescue Exception => e
            Rails.logger.error "Could not send email notifications: #{e.message}"
          end
        end
      else       
        @file.errors.each do |e, msg| 
          flash[:error] = msg         
        end
      end      
    end
    if commit
      redirect_to :back
    else
      redirect_to dmsf_folder_path(:id => @project, :folder_id => @file.folder)
    end    
  end

  def delete_revision    
    if @revision # && !@revision.deleted
      if @revision.delete(true)
        flash[:notice] = l(:notice_revision_deleted)
        log_activity('deleted')
      else        
        @revision.errors.each do |e, msg| 
          flash[:error] = msg
        end
      end
    end
    redirect_to :action => 'show', :id => @file
  end

  def lock
    if @file.locked?
      flash[:warning] = l(:warning_file_already_locked)
    else
      @file.lock!
      flash[:notice] = l(:notice_file_locked)
    end      
    redirect_to :back
  end
  
  def unlock
    unless @file.locked?
      flash[:warning] = l(:warning_file_not_locked)
    else
      if @file.locks[0].user == User.current || User.current.allowed_to?(:force_file_unlock, @file.project)
        @file.unlock!
        flash[:notice] = l(:notice_file_unlocked)
      else
        flash[:error] = l(:error_only_user_that_locked_file_can_unlock_it)
      end
    end    
    redirect_to :back
  end

  def notify_activate
    if @file.notification
      flash[:warning] = l(:warning_file_notifications_already_activated)
    else
      @file.notify_activate
      flash[:notice] = l(:notice_file_notifications_activated)
    end    
    redirect_to :back
  end
  
  def notify_deactivate
    unless @file.notification
      flash[:warning] = l(:warning_file_notifications_already_deactivated)
    else
      @file.notify_deactivate
      flash[:notice] = l(:notice_file_notifications_deactivated)
    end    
    redirect_to :back
  end
  
  def restore
    if @file.restore
      log_activity('restored')
      flash[:notice] = l(:notice_dmsf_file_restored)
    else
      flash[:error] = @file.errors.full_messages.to_sentence
    end
    redirect_to :back
  end

  private

  def log_activity(action)
    Rails.logger.info "#{Time.now.strftime('%Y-%m-%d %H:%M:%S')} #{User.current.login}@#{request.remote_ip}/#{request.env['HTTP_X_FORWARDED_FOR']}: #{action} dmsf://#{@file.project.identifier}/#{@file.id}/#{@revision.id if @revision}"
  end 
  
  def find_file    
    @file = DmsfFile.find params[:id]
    @project = @file.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_revision
    @revision = DmsfFileRevision.visible.find(params[:id])
    @file = @revision.file 
    @project = @file.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def check_project(entry)
    if entry && entry.project != @project
      raise DmsfAccessError, l(:error_entry_project_does_not_match_current_project) 
    end
  end
  
end

redmine_dmsf/app/views/dmsf_files/_revision_access.html.erb
<%#=
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011   Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012   Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>
<br/>
<table class="display access-table list">
  <thead>
    <tr>
      <th><%= l(:field_user) %></th>
      <th><%= l(:heading_access_downloads_emails) %></th>
      <th><%= l(:heading_access_first) %></th>
      <th><%= l(:heading_access_last) %></th>
    </tr>
  </thead>
  <tbody>
    <% revision.access_grouped.each do |access| %>
      <tr>
        <td><%= link_to_user(access.user) %></td>
        <td><%= access['count'] %></td>
        <td><%= format_time(DmsfHelper::to_time(access.first_at)) %></td>
        <td><%= format_time(DmsfHelper::to_time(access.last_at)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

redmine_dmsf/app/views/dmsf_files/show.html.erb
<%#=
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% html_title(l(:dmsf)) %>

<div class="contextual">
  <% if User.current.allowed_to?(:file_manipulation, @project) %>
    <% unless @file.locked? %>
       <%= link_to(l(:button_lock),
          lock_dmsf_files_path(:id => @file),
          :title => l(:title_lock_file),
          :class => 'icon icon-dmsf-lock') %>
      <% if @file.notification %>              
        <%= link_to(l(:label_notifications_off),
          notify_deactivate_dmsf_files_path(:id => @file),
          :title => l(:title_notifications_active_deactivate),
          :class => 'icon icon-notification-on') %>
      <% else %>              
        <%= link_to(l(:label_notifications_on),
          notify_activate_dmsf_files_path(:id => @file),
          :title => l(:title_notifications_not_active_activate),
          :class => 'icon icon-notification-off') %>
      <% end %>
      <%= link_to(l(:label_link_to), 
        new_dmsf_link_path(:project_id => @project.id, :dmsf_folder_id => @file.folder ? @file.folder.id : nil, :dmsf_file_id => @file.id, :type => 'link_to'),
        :title => l(:title_create_link), 
        :class => 'icon icon-link') %>
      <%= link_to("#{l(:button_copy)}/#{l(:button_move)}", copy_file_path(:id => @file),
        :title => l(:title_copy), :class => 'icon icon-copy') %>
      <%= delete_link @file if @file_delete_allowed %>
    <% else %>
      <% if (!@file.locked_for_user? || User.current.allowed_to?(:force_file_unlock, @project)) && @file.unlockable? %>
        <%= link_to(l(:button_unlock),
          unlock_dmsf_files_path(:id => @file),
          :title => l(:title_unlock_file),
          :class => 'icon icon-dmsf-unlock')%>        
      <% end %>        
    <% end %>   
  <% end %>
</div>

<%= render(:partial => '/dmsf/path', :locals => {:folder => @file.folder, :filename => @file.title}) %>  

<%= error_messages_for('file') %>
<%= error_messages_for('revision') %>
<%= render(:partial => 'file_new_revision') if User.current.allowed_to?(:file_manipulation, @file.project) %>

<h3><%= l(:heading_revisions) %></h3>
<% @file.revisions.visible[@revision_pages.offset,@revision_pages.per_page].each do |revision| %>
  <div class="revision_box dmsf_detail dataTables_wrapper">  
    <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix">	
      <div class="dataTables_lenght">
        <div class="controls" style="float: right">            
          <%= link_to_function(
            '', 
            "$('#revision_access-#{revision.id}').toggle()", 
            :title => l(:title_download_entries),
            :class => 'icon icon-dmsf-rev-downloads') %>
          <%= link_to('',            
            dmsf_file_path(@file, :download => revision),
            :title => l(:title_title_version_version_download, :title => h(revision.title), :version => revision.version),
            :class => 'icon icon-dmsf-rev-download') %>          
          <%= link_to '',
            delete_revision_path(revision),
            :data => {:confirm => l(:text_are_you_sure)},
            :title => l(:title_delete_revision),
            :class => 'icon icon-dmsf-rev-delete' if @file_delete_allowed %>          
        </div>      
        <i><%= l(:info_revision, :rev => revision.id) %></i>
        <%= (revision.source_revision.nil? ? l(:label_created) : l(:label_changed)).downcase %>
        <%= l(:info_changed_by_user, :changed => format_time(revision.updated_at)) %>
        <%=  link_to(revision.user) %>
      </div>
    </div>
    <div style="border: 1px solid #e4e4e4;">
      <div class="clear">
        <div class="splitcontentleft">			
          <%= label_tag('', "#{l(:label_title)}:") %>
          <%= h(revision.title) %>		
        </div>
        <div class="splitcontentright">			
          <%= label_tag('', "#{l(:label_file)}:") %>
          <%= ("#{h(revision.file.folder.dmsf_path_str)}/") if revision.file.folder %><%= h(revision.name) %>			
        </div>
      </div>
      <p class="no-ident">
        <%= label_tag('', "#{l(:label_description)}:") %>
      </p>
      <div class="wiki clear" style="margin-left: 110px">
        <%= textilizable(revision.description) %>
      </div>	
      <div class="splitcontentleft">		
        <%= label_tag('', "#{l(:label_version)}:") %>
        <%= revision.major_version %>.<%= revision.minor_version %>
        <br/>
        <%= label_tag('', "#{l(:link_workflow)}:") %>
        <% wf = DmsfWorkflow.find_by_id(revision.dmsf_workflow_id) %>
        <% if wf %>
          <%= "#{wf.name} - " %>
          <%= link_to(
            revision.workflow_str(false),
            log_dmsf_workflow_path(
              :project_id => @project.id, 
              :id => wf.id,                                 
              :dmsf_file_revision_id => revision.id),
            :title => DmsfWorkflow.assignments_to_users_str(wf.next_assignments(revision.id)),
            :remote => true) %>
        <% else %>
          <%= revision.workflow_str(true) %>
        <% end %>	
      </div>
      <div class="splitcontentright clear">		
        <%= label_tag('', "#{l(:label_mime)}:") %>
        <%= h(revision.mime_type) %>&nbsp;
        <br/>
        <%= label_tag('', "#{l(:label_size)}:") %>
        <%= number_to_human_size(revision.size) %>		
      </div>	
      <div class="no-ident clear">
        <%= render 'dmsf/custom_fields', :object => revision %>
      </div>
      <p class="no-ident">
        <%= label_tag('', "#{l(:label_comment)}:") %>
      </p>
      <div class="wiki clear" style="margin-left: 110px">
        <%= textilizable(revision.comment) %>
      </div>	     	           
      <div id="<%= "revision_access-#{revision.id}" %>" style="display:none">        
        <%= render(:partial => 'revision_access', :locals => {:revision => revision}) if User.current.allowed_to?(:file_manipulation, @file.project) %>        
      </div>    
    </div>
  </div>  
  <br/>  
<% end %>

<p class="pagination"><%= pagination_links_full @revision_pages, @file.revisions.visible.count %></p>

<%
  url = 'jquery.dataTables/en.json'
  url = "jquery.dataTables/#{I18n.locale.to_s.downcase}.json" if I18n.locale && !I18n.locale.to_s.match(/^en.*/)
%>

<script type="text/javascript">
  $('a.delete-revision').click(function(event) {
    if(!window.confirm('<%= l(:text_are_you_sure) %>')) {
      event.preventDefault();
    }
  });

  $('a.delete-entry').click(function(event) {
    if(!window.confirm('<%= l(:text_are_you_sure) %>')) {
      event.preventDefault();      
    }
  });

  $('#file_upload').change(function() {
    if($("input[name='version']:checked").val() == '0') {
      $('#fileMinorVersionRadio').prop('checked', true); 
    }
    $('#fileSameVersionRadio').prop('disabled', true); 
  });  

  $('#newRevisionFormContentToggle').click(function() {
    if($('#newRevisionFormContent').is(':visible')) {
      $(this).text('[+]');
      $('#newRevisionFormContent').hide();
    }
    else {
      $(this).text('[-]');
      $('#newRevisionFormContent').show();
    }    
  });

  $('.access-table').dataTable({
    'bJQueryUI': true,
    'oLanguage': {
      'sUrl': '/plugin_assets/<%= :redmine_dmsf %>/javascripts/<%= url %>'	
    }
  });
</script>
<% if @revision.valid? && @file.valid? %>
  <script type="text/javascript">
    $('#newRevisionFormContentToggle').text('[+]');    
    $('#newRevisionFormContent').hide();    
  </script>
<% end %>

<% content_for :header_tags do %>  
  <%= stylesheet_link_tag 'jquery.dataTables/jquery-ui.dataTables.css', :plugin => 'redmine_dmsf' %>  
  <%= javascript_include_tag 'jquery.dataTables/jquery.dataTables.min.js', :plugin => 'redmine_dmsf' %>  
<% end %>